cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@marinha.mil.br
      name: admin
      password: $2b$12$W6843k2P5LS.8NRXqqnKMOP2mczQGw5Av7NT/o8X88vKSFdS7pBau
    depsmrj:
      email: depsmrj@marinha.mil.br
      name: "Dep\xF3sito de Sobressalentes da Marinha no Rio de Janeiro"
      password: $2b$12$rMJpZtT/b9.IKmKKKEASqeGUEco7M0Nu/uvlrdweWo/cHowLSL0iu
preauthorized:
  names:
  - admin
